; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: -p --version 6
; RUN: opt -S -passes='loop-unroll<O3;runtime>' < %s | FileCheck %s


define void @openmp_loop(
; CHECK-LABEL: define void @openmp_loop(ptr %lower_bound_ptr, ptr %denominator_ptr, i64 %outer_limit) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label %outer
; CHECK:       outer:
; CHECK-NEXT:    %outer_index = phi i64 [ 0, %entry ], [ %next_outer_index, %outer_latch ]
; CHECK-NEXT:    %lower_bound_i32 = load i32, ptr %lower_bound_ptr, align 4
; CHECK-NEXT:    %denominator_i32 = load i32, ptr %denominator_ptr, align 4
; CHECK-NEXT:    %lower_bound = zext i32 %lower_bound_i32 to i64
; CHECK-NEXT:    %denominator = zext i32 %denominator_i32 to i64
; CHECK-NEXT:    %lower_bound_too_large = icmp ugt i32 %lower_bound_i32, 35
; CHECK-NEXT:    br i1 %lower_bound_too_large, label %outer_latch, label %compute_trip_count
; CHECK:       compute_trip_count:
; CHECK-NEXT:    %difference = sub nsw i64 %denominator, %lower_bound
; CHECK-NEXT:    %numerator = add nsw i64 %difference, 35
; CHECK-NEXT:    %quotient = udiv i64 %numerator, %denominator
; CHECK-NEXT:    %skip_inner = icmp ult i64 %numerator, %denominator
; CHECK-NEXT:    br i1 %skip_inner, label %outer_latch, label %inner.preheader
; CHECK:       inner.preheader:
; CHECK-NEXT:    br label %inner
; CHECK:       inner:
; CHECK-NEXT:    %count = phi i64 [ %next, %inner ], [ %quotient, %inner.preheader ]
; CHECK-NEXT:    %offset = phi i64 [ %next_offset, %inner ], [ 0, %inner.preheader ]
; CHECK-NEXT:    %next = add i64 %count, -1
; CHECK-NEXT:    %next_offset = add i64 %offset, %denominator
; CHECK-NEXT:    %continue = icmp ugt i64 %count, 1
; CHECK-NEXT:    br i1 %continue, label %inner, label %outer_latch.loopexit
; CHECK:       outer_latch.loopexit:
; CHECK-NEXT:    br label %outer_latch
; CHECK:       outer_latch:
; CHECK-NEXT:    call void @barrier()
; CHECK-NEXT:    %next_outer_index = add i64 %outer_index, 1
; CHECK-NEXT:    %continue_outer = icmp ult i64 %next_outer_index, %outer_limit
; CHECK-NEXT:    br i1 %continue_outer, label %outer, label %exit
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
  ptr %lower_bound_ptr, ptr %denominator_ptr, i64 %outer_limit) {
entry:
  br label %outer

outer:
  %outer_index = phi i64 [ 0, %entry ], [ %next_outer_index, %outer_latch ]
  %lower_bound_i32 = load i32, ptr %lower_bound_ptr
  %denominator_i32 = load i32, ptr %denominator_ptr
  %lower_bound = zext i32 %lower_bound_i32 to i64
  %denominator = zext i32 %denominator_i32 to i64
  %lower_bound_too_large = icmp ugt i32 %lower_bound_i32, 35
  br i1 %lower_bound_too_large, label %outer_latch, label %compute_trip_count

compute_trip_count:
  %difference = sub nsw i64 %denominator, %lower_bound
  %numerator = add nsw i64 %difference, 35
  %quotient = udiv i64 %numerator, %denominator
  %skip_inner = icmp ult i64 %numerator, %denominator
  br i1 %skip_inner, label %outer_latch, label %inner

inner:
  %count = phi i64 [ %next, %inner ], [ %quotient, %compute_trip_count ]
  %offset = phi i64 [ %next_offset, %inner ], [ 0, %compute_trip_count ]
  %next = add i64 %count, -1
  %next_offset = add i64 %offset, %denominator
  %continue = icmp ugt i64 %count, 1
  br i1 %continue, label %inner, label %outer_latch

outer_latch:
  call void @barrier()
  %next_outer_index = add i64 %outer_index, 1
  %continue_outer = icmp ult i64 %next_outer_index, %outer_limit
  br i1 %continue_outer, label %outer, label %exit

exit:
  ret void
}

declare void @barrier() convergent noduplicate


define void @udiv_entry_guard_reduced(ptr %denominator_ptr) {
; CHECK-LABEL: define void @udiv_entry_guard_reduced(ptr %denominator_ptr) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label %outer
; CHECK:       outer.loopexit:
; CHECK-NEXT:    br label %outer.backedge
; CHECK:       outer:
; CHECK-NEXT:    %denominator = load i64, ptr %denominator_ptr, align 4
; CHECK-NEXT:    %quotient = udiv i64 35, %denominator
; CHECK-NEXT:    %skip_inner = icmp ult i64 35, %denominator
; CHECK-NEXT:    br i1 %skip_inner, label %outer.backedge, label %inner.preheader
; CHECK:       outer.backedge:
; CHECK-NEXT:    br label %outer
; CHECK:       inner.preheader:
; CHECK-NEXT:    br label %inner
; CHECK:       inner:
; CHECK-NEXT:    %count = phi i64 [ %next, %inner ], [ %quotient, %inner.preheader ]
; CHECK-NEXT:    %next = add i64 %count, -1
; CHECK-NEXT:    %continue = icmp ugt i64 %count, 1
; CHECK-NEXT:    br i1 %continue, label %inner, label %outer.loopexit
;
entry:
  br label %outer

outer:                                            ; preds = %inner, %outer, %entry
  %denominator = load i64, ptr %denominator_ptr
  %quotient = udiv i64 35, %denominator
  %skip_inner = icmp ult i64 35, %denominator
  br i1 %skip_inner, label %outer, label %inner

inner:                                            ; preds = %inner, %outer
  %count = phi i64 [ %next, %inner ], [ %quotient, %outer ]
  %next = add i64 %count, -1
  %continue = icmp ugt i64 %count, 1
  br i1 %continue, label %inner, label %outer
}
