; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: -p --version 6
; RUN: opt < %s -S -passes='loop(indvars)' | FileCheck %s --check-prefix=INDVARS

define i1 @quotient_eq_zero(i64 %a, i64 %b) {
; INDVARS-LABEL: define i1 @quotient_eq_zero(i64 %a, i64 %b) {
; INDVARS-NEXT:  entry:
; INDVARS-NEXT:    %q = udiv i64 %a, %b
; INDVARS-NEXT:    %guard = icmp eq i64 %q, 0
; INDVARS-NEXT:    br i1 %guard, label %loop.preheader, label %exit
; INDVARS:       loop.preheader:
; INDVARS-NEXT:    br label %loop
; INDVARS:       loop:
; INDVARS-NEXT:    %cmp = icmp ult i64 %a, %b
; INDVARS-NEXT:    br i1 false, label %loop, label %exit.loopexit
; INDVARS:       exit.loopexit:
; INDVARS-NEXT:    %cmp.lcssa = phi i1 [ %cmp, %loop ]
; INDVARS-NEXT:    br label %exit
; INDVARS:       exit:
; INDVARS-NEXT:    %result = phi i1 [ false, %entry ], [ %cmp.lcssa, %exit.loopexit ]
; INDVARS-NEXT:    ret i1 %result
;
entry:
  %q = udiv i64 %a, %b
  %guard = icmp eq i64 %q, 0
  br i1 %guard, label %loop, label %exit

loop:
  %same = phi i64 [ %a, %entry ], [ %same.next, %loop ]
  %cmp = icmp ult i64 %same, %b
  %same.next = add i64 %a, 0
  br i1 false, label %loop, label %exit

exit:
  %result = phi i1 [ false, %entry ], [ %cmp, %loop ]
  ret i1 %result
}

define i1 @quotient_ule_zero(i64 %a, i64 %b) {
; INDVARS-LABEL: define i1 @quotient_ule_zero(i64 %a, i64 %b) {
; INDVARS-NEXT:  entry:
; INDVARS-NEXT:    %q = udiv i64 %a, %b
; INDVARS-NEXT:    %guard = icmp ule i64 %q, 0
; INDVARS-NEXT:    br i1 %guard, label %loop.preheader, label %exit
; INDVARS:       loop.preheader:
; INDVARS-NEXT:    br label %loop
; INDVARS:       loop:
; INDVARS-NEXT:    %cmp = icmp ult i64 %a, %b
; INDVARS-NEXT:    br i1 false, label %loop, label %exit.loopexit
; INDVARS:       exit.loopexit:
; INDVARS-NEXT:    %cmp.lcssa = phi i1 [ %cmp, %loop ]
; INDVARS-NEXT:    br label %exit
; INDVARS:       exit:
; INDVARS-NEXT:    %result = phi i1 [ false, %entry ], [ %cmp.lcssa, %exit.loopexit ]
; INDVARS-NEXT:    ret i1 %result
;
entry:
  %q = udiv i64 %a, %b
  %guard = icmp ule i64 %q, 0
  br i1 %guard, label %loop, label %exit

loop:
  %same = phi i64 [ %a, %entry ], [ %same.next, %loop ]
  %cmp = icmp ult i64 %same, %b
  %same.next = add i64 %a, 0
  br i1 false, label %loop, label %exit

exit:
  %result = phi i1 [ false, %entry ], [ %cmp, %loop ]
  ret i1 %result
}

define i1 @quotient_ult_one(i64 %a, i64 %b) {
; INDVARS-LABEL: define i1 @quotient_ult_one(i64 %a, i64 %b) {
; INDVARS-NEXT:  entry:
; INDVARS-NEXT:    %q = udiv i64 %a, %b
; INDVARS-NEXT:    %guard = icmp ult i64 %q, 1
; INDVARS-NEXT:    br i1 %guard, label %loop.preheader, label %exit
; INDVARS:       loop.preheader:
; INDVARS-NEXT:    br label %loop
; INDVARS:       loop:
; INDVARS-NEXT:    %cmp = icmp ult i64 %a, %b
; INDVARS-NEXT:    br i1 false, label %loop, label %exit.loopexit
; INDVARS:       exit.loopexit:
; INDVARS-NEXT:    %cmp.lcssa = phi i1 [ %cmp, %loop ]
; INDVARS-NEXT:    br label %exit
; INDVARS:       exit:
; INDVARS-NEXT:    %result = phi i1 [ false, %entry ], [ %cmp.lcssa, %exit.loopexit ]
; INDVARS-NEXT:    ret i1 %result
;
entry:
  %q = udiv i64 %a, %b
  %guard = icmp ult i64 %q, 1
  br i1 %guard, label %loop, label %exit

loop:
  %same = phi i64 [ %a, %entry ], [ %same.next, %loop ]
  %cmp = icmp ult i64 %same, %b
  %same.next = add i64 %a, 0
  br i1 false, label %loop, label %exit

exit:
  %result = phi i1 [ false, %entry ], [ %cmp, %loop ]
  ret i1 %result
}

define i1 @quotient_ne_zero(i64 %a, i64 %b) {
; INDVARS-LABEL: define i1 @quotient_ne_zero(i64 %a, i64 %b) {
; INDVARS-NEXT:  entry:
; INDVARS-NEXT:    %q = udiv i64 %a, %b
; INDVARS-NEXT:    %guard = icmp ne i64 %q, 0
; INDVARS-NEXT:    br i1 %guard, label %loop.preheader, label %exit
; INDVARS:       loop.preheader:
; INDVARS-NEXT:    br label %loop
; INDVARS:       loop:
; INDVARS-NEXT:    %cmp = icmp uge i64 %a, %b
; INDVARS-NEXT:    br i1 false, label %loop, label %exit.loopexit
; INDVARS:       exit.loopexit:
; INDVARS-NEXT:    %cmp.lcssa = phi i1 [ %cmp, %loop ]
; INDVARS-NEXT:    br label %exit
; INDVARS:       exit:
; INDVARS-NEXT:    %result = phi i1 [ false, %entry ], [ %cmp.lcssa, %exit.loopexit ]
; INDVARS-NEXT:    ret i1 %result
;
entry:
  %q = udiv i64 %a, %b
  %guard = icmp ne i64 %q, 0
  br i1 %guard, label %loop, label %exit

loop:
  %same = phi i64 [ %a, %entry ], [ %same.next, %loop ]
  %cmp = icmp uge i64 %same, %b
  %same.next = add i64 %a, 0
  br i1 false, label %loop, label %exit

exit:
  %result = phi i1 [ false, %entry ], [ %cmp, %loop ]
  ret i1 %result
}

define i1 @quotient_ugt_zero(i64 %a, i64 %b) {
; INDVARS-LABEL: define i1 @quotient_ugt_zero(i64 %a, i64 %b) {
; INDVARS-NEXT:  entry:
; INDVARS-NEXT:    %q = udiv i64 %a, %b
; INDVARS-NEXT:    %guard = icmp ugt i64 %q, 0
; INDVARS-NEXT:    br i1 %guard, label %loop.preheader, label %exit
; INDVARS:       loop.preheader:
; INDVARS-NEXT:    br label %loop
; INDVARS:       loop:
; INDVARS-NEXT:    %cmp = icmp uge i64 %a, %b
; INDVARS-NEXT:    br i1 false, label %loop, label %exit.loopexit
; INDVARS:       exit.loopexit:
; INDVARS-NEXT:    %cmp.lcssa = phi i1 [ %cmp, %loop ]
; INDVARS-NEXT:    br label %exit
; INDVARS:       exit:
; INDVARS-NEXT:    %result = phi i1 [ false, %entry ], [ %cmp.lcssa, %exit.loopexit ]
; INDVARS-NEXT:    ret i1 %result
;
entry:
  %q = udiv i64 %a, %b
  %guard = icmp ugt i64 %q, 0
  br i1 %guard, label %loop, label %exit

loop:
  %same = phi i64 [ %a, %entry ], [ %same.next, %loop ]
  %cmp = icmp uge i64 %same, %b
  %same.next = add i64 %a, 0
  br i1 false, label %loop, label %exit

exit:
  %result = phi i1 [ false, %entry ], [ %cmp, %loop ]
  ret i1 %result
}

define i1 @quotient_uge_one(i64 %a, i64 %b) {
; INDVARS-LABEL: define i1 @quotient_uge_one(i64 %a, i64 %b) {
; INDVARS-NEXT:  entry:
; INDVARS-NEXT:    %q = udiv i64 %a, %b
; INDVARS-NEXT:    %guard = icmp uge i64 %q, 1
; INDVARS-NEXT:    br i1 %guard, label %loop.preheader, label %exit
; INDVARS:       loop.preheader:
; INDVARS-NEXT:    br label %loop
; INDVARS:       loop:
; INDVARS-NEXT:    %cmp = icmp uge i64 %a, %b
; INDVARS-NEXT:    br i1 false, label %loop, label %exit.loopexit
; INDVARS:       exit.loopexit:
; INDVARS-NEXT:    %cmp.lcssa = phi i1 [ %cmp, %loop ]
; INDVARS-NEXT:    br label %exit
; INDVARS:       exit:
; INDVARS-NEXT:    %result = phi i1 [ false, %entry ], [ %cmp.lcssa, %exit.loopexit ]
; INDVARS-NEXT:    ret i1 %result
;
entry:
  %q = udiv i64 %a, %b
  %guard = icmp uge i64 %q, 1
  br i1 %guard, label %loop, label %exit

loop:
  %same = phi i64 [ %a, %entry ], [ %same.next, %loop ]
  %cmp = icmp uge i64 %same, %b
  %same.next = add i64 %a, 0
  br i1 false, label %loop, label %exit

exit:
  %result = phi i1 [ false, %entry ], [ %cmp, %loop ]
  ret i1 %result
}

define i1 @constant_on_left(i64 %a, i64 %b) {
; INDVARS-LABEL: define i1 @constant_on_left(i64 %a, i64 %b) {
; INDVARS-NEXT:  entry:
; INDVARS-NEXT:    %q = udiv i64 %a, %b
; INDVARS-NEXT:    %guard = icmp ult i64 0, %q
; INDVARS-NEXT:    br i1 %guard, label %loop.preheader, label %exit
; INDVARS:       loop.preheader:
; INDVARS-NEXT:    br label %loop
; INDVARS:       loop:
; INDVARS-NEXT:    %cmp = icmp uge i64 %a, %b
; INDVARS-NEXT:    br i1 false, label %loop, label %exit.loopexit
; INDVARS:       exit.loopexit:
; INDVARS-NEXT:    %cmp.lcssa = phi i1 [ %cmp, %loop ]
; INDVARS-NEXT:    br label %exit
; INDVARS:       exit:
; INDVARS-NEXT:    %result = phi i1 [ false, %entry ], [ %cmp.lcssa, %exit.loopexit ]
; INDVARS-NEXT:    ret i1 %result
;
entry:
  %q = udiv i64 %a, %b
  %guard = icmp ult i64 0, %q
  br i1 %guard, label %loop, label %exit

loop:
  %same = phi i64 [ %a, %entry ], [ %same.next, %loop ]
  %cmp = icmp uge i64 %same, %b
  %same.next = add i64 %a, 0
  br i1 false, label %loop, label %exit

exit:
  %result = phi i1 [ false, %entry ], [ %cmp, %loop ]
  ret i1 %result
}
